
## Imbalanced Classification

In [3]:
import numpy as np
import pandas as pd

In [4]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [68]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score
import warnings

In [5]:
df = pd.read_csv("/Users/alexandraasinovsky/Downloads/talkingdata-adtracking-fraud-detection/train_sample.csv")

In [35]:
df['hh']  = pd.to_datetime(df.click_time).dt.hour.astype('uint8')
X = df.drop(['click_time', 'attributed_time', 'is_attributed'], axis=1)

In [36]:
y = df['is_attributed']

In [60]:
over = RandomOverSampler(sampling_strategy=0.5)
under = RandomUnderSampler(sampling_strategy=0.5)
warnings.filterwarnings('ignore')
d_1 = {"Model": ['Logistic Regression','Support Vector Classification', 'Random Forest', 'Gradient Boosting'], "Oversampling": [], "Undersampling": []}
d_2 = {"Model": ['Logistic Regression','Support Vector Classification', 'Random Forest', 'Gradient Boosting'],"Oversampling": [], "Undersampling": []}
d_3 = {"Model": ['Logistic Regression','Support Vector Classification', 'Random Forest', 'Gradient Boosting'],"Oversampling": [], "Undersampling": []}
d_4 = {"Model": ['Logistic Regression','Support Vector Classification', 'Random Forest', 'Gradient Boosting'],"Oversampling": [], "Undersampling": []}


## Monte Carlo

I'm using oversampling to find coefficients for logistic regression 

In [47]:
cv = RepeatedStratifiedKFold(n_splits=10, random_state=1)
scores = {'f1': 'f1_micro', 'auc': 'roc_auc','precision': 'precision', 'recall': 'recall'}

X_over, y_over = over.fit_resample(X, y)

In [67]:
clf = LogisticRegression(random_state=0, max_iter=1000).fit(X_over, y_over)

In [52]:
clf.coef_

array([[ 7.19702804e-06,  4.27908285e-02, -3.44999269e-04,
        -2.24833243e-03, -6.66263911e-03, -6.68023309e-02]])

In [72]:
scores = cross_val_score(clf, X, y, cv=10, scoring='precision')

In [73]:
scores

array([0.9978, 0.9978, 0.9978, 0.9977, 0.9977, 0.9977, 0.9977, 0.9976,
       0.9977, 0.9977])

In [74]:
f1 = cross_val_score(clf, X, y, scoring='f1_micro', cv=cv)
auc = cross_val_score(clf, X, y, scoring='roc_auc', cv=cv)
pres = cross_val_score(clf, X, y, scoring='precision', cv=cv)
rec = cross_val_score(clf, X, y, scoring='recall', cv=cv)

In [75]:
pres

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
scores_m = {'f1': np.mean(f1['test_score']) , 'test_auc': np.mean(auc['test_score']) , 'test_precision': np.mean(pres['test_score']) , 'test_recall': np.mean(rec['test_score']) }


In [63]:
d = pd.DataFrame(scores_m, index=[0])
d

f1  test_auc  test_precision  test_recall
0  0.997715  0.624699             0.0          0.0

In [34]:
df

ip  app  device  os  channel           click_time attributed_time  \
0       87540   12       1  13      497  2017-11-07 09:30:38             NaN   
1      105560   25       1  17      259  2017-11-07 13:40:27             NaN   
2      101424   12       1  19      212  2017-11-07 18:05:24             NaN   
3       94584   13       1  13      477  2017-11-07 04:58:08             NaN   
4       68413   12       1   1      178  2017-11-09 09:00:09             NaN   
...       ...  ...     ...  ..      ...                  ...             ...   
99995  124883   11       1  19      122  2017-11-09 13:25:41             NaN   
99996   85150    9       1  13      244  2017-11-07 11:25:43             NaN   
99997   18839    3       1  13       19  2017-11-08 11:38:42             NaN   
99998  114276   15       1  12      245  2017-11-08 17:55:21             NaN   
99999  119349   14       1  15      401  2017-11-07 14:32:27             NaN   

       is_attributed  hh  
0                  0   9  
1                  0  13  
2                  0  18  
3                  0   4  
4                  0   9  
...              ...  ..  
99995              0  13  
99996              0  11  
99997              0  11  
99998              0  17  
99999              0  14  

[100000 rows x 9 columns]

In [14]:
pipe.fit(X_train, y_train)
pipe.predict(X_test)


ip  app  os  channel  hh
3582     3804   64  18      459   9
60498  169013   25  19      259  14
53227   75007    2  10      237   7
21333   25676   14  13      442  12
3885     5299    3  13      280   9
...       ...  ...  ..      ...  ..
26543   43827    9  10      134   0
85764   44067   15   3      278   8
87585   70347   23  19      153   1
32519    5314   15  19      140  17
18831   23524    3  19      205   6

[25000 rows x 5 columns]

### Logistic regression

In [8]:
steps_lr_o = [('o', over),  ('m', LogisticRegression(solver = 'lbfgs', max_iter=1000))]
pipeline_lr_o = Pipeline(steps=steps_lr_o)



scores_lr_o = cross_validate(pipeline_lr_o, X, y, scoring=scores, cv=cv)

In [9]:
score_lr_f1_o = np.mean(scores_lr_o['test_f1'])
d_1["Oversampling"].append(score_lr_f1_o)

score_lr_auc_o = np.mean(scores_lr_o['test_auc'])
d_2["Oversampling"].append(score_lr_auc_o)

score_lr_prec_o = np.mean(scores_lr_o['test_precision'])
d_3["Oversampling"].append(score_lr_prec_o)

score_lr_rec_o = np.mean(scores_lr_o['test_recall'])
d_4["Oversampling"].append(score_lr_rec_o)

s = 'F1 Score of Logistic regressiion with oversampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_lr_f1_o , score_lr_auc_o, score_lr_prec_o, score_lr_rec_o)
print(s)

F1 Score of Logistic regressiion with oversampling: 0.86402, auc: 0.81220, precision: 0.01057, recall: 0.61937


In [10]:
steps_lr_u = [('u', under),  ('m', LogisticRegression(solver = 'lbfgs', max_iter=1000))]
pipeline_lr_u = Pipeline(steps=steps_lr_u)

scores_lr_u = cross_validate(pipeline_lr_u, X, y, scoring=scores, cv=cv)

score_lr_f1_u = np.mean(scores_lr_u['test_f1'])
d_1["Undersampling"].append(score_lr_f1_u)

score_lr_auc_u = np.mean(scores_lr_u['test_auc'])
d_2["Undersampling"].append(np.mean(score_lr_auc_u))

score_lr_prec_u = np.mean(scores_lr_u['test_precision'])
d_3["Undersampling"].append(score_lr_prec_u)

score_lr_rec_u = np.mean(scores_lr_u['test_recall'])
d_4["Undersampling"].append(score_lr_rec_u)

s = 'F1 Score of Logistic regressiion with undersampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_lr_f1_u , score_lr_auc_u, score_lr_prec_u, score_lr_rec_u)
print(s)

F1 Score of Logistic regressiion with undersampling: 0.85976, auc: 0.81059, precision: 0.01006, recall: 0.61623


### Support Vector Classification

In [11]:
steps_svc_o = [('o', over),  ('m', SGDClassifier(max_iter=1000, tol=1e-3))]
pipeline_svc_o = Pipeline(steps=steps_svc_o)

scores_svc_o = cross_validate(pipeline_svc_o, X, y, scoring=scores, cv=cv)

score_svc_f1_o = np.mean(scores_svc_o['test_f1'])
d_1["Oversampling"].append(score_svc_f1_o)

score_svc_auc_o = np.mean(scores_svc_o['test_auc'])
d_2["Oversampling"].append(score_svc_auc_o)

score_svc_prec_o = np.mean(scores_svc_o['test_precision'])
d_3["Oversampling"].append(score_svc_prec_o)

score_svc_rec_o = np.mean(scores_svc_o['test_recall'])
d_4["Oversampling"].append(score_svc_rec_o)

s = 'F1 Score of SVC with oversampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_svc_f1_o , score_svc_auc_o, score_svc_prec_o, score_svc_rec_o)
print(s)


F1 Score of SVC with oversampling: 0.70024, auc: 0.71246, precision: 0.01704, recall: 0.56648


In [12]:
steps_svc_u = [('u', under),  ('m', SGDClassifier(max_iter=1000, tol=1e-3))]
pipeline_svc_u = Pipeline(steps=steps_svc_u)


scores_svc_u = cross_validate(pipeline_svc_u, X, y, scoring=scores, cv=cv)

score_svc_f1_u = np.mean(scores_svc_u['test_f1'])
d_1["Undersampling"].append(score_svc_f1_u)

score_svc_auc_u = np.mean(scores_svc_u['test_auc'])
d_2["Undersampling"].append(score_svc_auc_u)

score_svc_prec_u = np.mean(scores_svc_u['test_precision'])
d_3["Undersampling"].append(score_svc_prec_u)

score_svc_rec_u = np.mean(scores_svc_u['test_recall'])
d_4["Undersampling"].append(score_svc_rec_u)

s = 'F1 Score of SVC with undersampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_svc_f1_u , score_svc_auc_u, score_svc_prec_u, score_svc_rec_u)
print(s)

F1 Score of SVC with undersampling: 0.53028, auc: 0.51833, precision: 0.00122, recall: 0.48644


### Random forest


In [13]:
steps_rf_o = [('o', over),  ('m', RandomForestClassifier(n_estimators=10, max_depth=None, min_samples_split=2, random_state=0))]
pipeline_rf_o = Pipeline(steps=steps_rf_o)

scores_rf_o = cross_validate(pipeline_rf_o, X, y, scoring=scores, cv=cv)

score_rf_f1_o = np.mean(scores_rf_o['test_f1'])
d_1["Oversampling"].append(score_rf_f1_o)

score_rf_auc_o = np.mean(scores_rf_o['test_auc'])
d_2["Oversampling"].append(score_rf_auc_o)

score_rf_prec_o = np.mean(scores_rf_o['test_precision'])
d_3["Oversampling"].append(score_rf_prec_o)

score_rf_rec_o = np.mean(scores_rf_o['test_recall'])
d_4["Oversampling"].append(score_rf_rec_o)

s = 'F1 Score of Random Forest with oversampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_rf_f1_o , score_rf_auc_o, score_rf_prec_o, score_rf_rec_o)
print(s)


F1 Score of Random Forest with oversampling: 0.99772, auc: 0.83579, precision: 0.50084, recall: 0.30022


In [14]:
steps_rf_u = [('u', under),  ('m', RandomForestClassifier(n_estimators=10, max_depth=None, min_samples_split=2, random_state=0))]
pipeline_rf_u = Pipeline(steps=steps_rf_u)

scores_rf_u = cross_validate(pipeline_rf_u, X, y, scoring=scores, cv=cv)

score_rf_f1_u = np.mean(scores_rf_u['test_f1'])
d_1["Undersampling"].append(score_rf_f1_u)

score_rf_auc_u = np.mean(scores_rf_o['test_auc'])
d_2["Undersampling"].append(score_rf_auc_u)

score_rf_prec_u = np.mean(scores_rf_o['test_precision'])
d_3["Undersampling"].append(score_rf_prec_u)

score_rf_rec_u = np.mean(scores_rf_o['test_recall'])
d_4["Undersampling"].append(score_rf_rec_u)

s = 'F1 Score of Random Forest with undersampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_rf_f1_u , score_rf_auc_u, score_rf_prec_u, score_rf_rec_u)
print(s)


F1 Score of Random Forest with undersampling: 0.96414, auc: 0.83579, precision: 0.50084, recall: 0.30022


### Gradient Boosting

In [15]:
steps_gb_o = [('o', over),  ('m', GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0))]
pipeline_gb_o = Pipeline(steps=steps_gb_o)

scores_gb_o = cross_validate(pipeline_gb_o, X, y, scoring=scores, cv=cv)

score_gb_f1_o = np.mean(scores_gb_o['test_f1'])
d_1["Oversampling"].append(score_gb_f1_o)

score_gb_auc_o = np.mean(scores_gb_o['test_auc'])
d_2["Oversampling"].append(score_rf_auc_o)

score_gb_prec_o = np.mean(scores_gb_o['test_precision'])
d_3["Oversampling"].append(score_gb_prec_o)

score_gb_rec_o = np.mean(scores_gb_o['test_recall'])
d_4["Oversampling"].append(score_gb_rec_o)

s = 'F1 Score of Gradient Boosting with oversampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_gb_f1_o , score_gb_auc_o, score_gb_prec_o, score_gb_rec_o)
print(s)



F1 Score of Gradient Boosting with oversampling: 0.97285, auc: 0.95857, precision: 0.07302, recall: 0.86362


In [16]:
steps_gb_u = [('u', under),  ('m', GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0))]
pipeline_gb_u = Pipeline(steps=steps_gb_u)

scores_gb_u = cross_validate(pipeline_gb_u, X, y, scoring=scores, cv=cv)

score_gb_f1_u = np.mean(scores_gb_u['test_f1'])
d_1["Undersampling"].append(score_gb_f1_u)

score_gb_auc_u = np.mean(scores_gb_u['test_auc'])
d_2["Undersampling"].append(score_gb_auc_u)

score_gb_prec_u = np.mean(scores_gb_u['test_precision'])
d_3["Undersampling"].append(score_gb_prec_u)

score_gb_rec_u = np.mean(scores_gb_u['test_recall'])
d_4["Undersampling"].append(score_gb_rec_u)

s = 'F1 Score of Gradient Boosting with undersampling: %.5f, auc: %.5f, precision: %.5f, recall: %.5f' % (score_gb_f1_u , score_gb_auc_u, score_gb_prec_u, score_gb_rec_u)
print(s)


F1 Score of Gradient Boosting with undersampling: 0.95262, auc: 0.94435, precision: 0.04422, recall: 0.86490


### Models comparison

In [17]:
# f1
df_1 = pd.DataFrame().from_dict(d_1)
df_1

Model  Oversampling  Undersampling
0            Logistic Regression      0.864016       0.859763
1  Support Vector Classification      0.700239       0.530277
2                  Random Forest      0.997719       0.964141
3              Gradient Boosting      0.972854       0.952616

In [18]:
# auc
df_2 = pd.DataFrame().from_dict(d_2)
df_2

Model  Oversampling  Undersampling
0            Logistic Regression      0.812201       0.810588
1  Support Vector Classification      0.712464       0.518329
2                  Random Forest      0.835786       0.835786
3              Gradient Boosting      0.835786       0.944345

In [19]:
# precision
df_3 = pd.DataFrame().from_dict(d_3)
df_3

Model  Oversampling  Undersampling
0            Logistic Regression      0.010572       0.010055
1  Support Vector Classification      0.017043       0.001220
2                  Random Forest      0.500843       0.500843
3              Gradient Boosting      0.073018       0.044221

In [20]:
# recall
df_4 = pd.DataFrame().from_dict(d_4)
df_4

Model  Oversampling  Undersampling
0            Logistic Regression      0.619368       0.616225
1  Support Vector Classification      0.566482       0.486443
2                  Random Forest      0.300217       0.300217
3              Gradient Boosting      0.863617       0.864901

It looks like Random forest perform the best where it comes to precision with oversampling and undersampling, but recall is best in Gradient Boosting. 